services:
  - type: web
    name: app-store-price
    runtime: docker
    plan: free
    region: singapore
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/v2/storefronts
    autoDeployTrigger: checksPass
    envVars:
      - key: PORT
        value: '8080'
      - key: JAVA_TOOL_OPTIONS
        value: '-XX:MaxRAMPercentage=50.0 -XX:InitialRAMPercentage=10.0 -XX:+ExitOnOutOfMemoryError'
      - key: APPSTORE_FETCH_CONCURRENCY
        value: '4'
      - key: APPSTORE_MAX_QUERIES
        value: '4'
